import { Trip, Flight, Hotel, CarRental, Activity, BudgetItem, ChecklistItem } from '../types';

export const sampleTrip: Trip = {
  id: 'trip-amsterdam-2026',
  name: 'טיול לאמסטרדם',
  destination: 'אמסטרדם, הולנד',
  startDate: '2026-08-15',
  endDate: '2026-08-22',
  currency: 'EUR',
  notes: 'טיול משפחתי לאמסטרדם — מוזיאונים, תעלות, ואופניים!',
  totalBudget: 12000,
};

export const sampleFlights: Flight[] = [
  {
    id: 'fl-1',
    tripId: 'trip-amsterdam-2026',
    type: 'outbound',
    airline: 'EL AL',
    flightNumber: 'LY315',
    from: 'תל אביב (TLV)',
    to: 'אמסטרדם (AMS)',
    departure: '2026-08-15T06:30',
    arrival: '2026-08-15T10:15',
    price: 1850,
    currency: 'ILS',
    confirmation: 'ELAL-7X9K2',
    notes: 'כבודה עד 23 ק"ג',
  },
  {
    id: 'fl-2',
    tripId: 'trip-amsterdam-2026',
    type: 'return',
    airline: 'EL AL',
    flightNumber: 'LY316',
    from: 'אמסטרדם (AMS)',
    to: 'תל אביב (TLV)',
    departure: '2026-08-22T11:45',
    arrival: '2026-08-22T17:30',
    price: 1850,
    currency: 'ILS',
    confirmation: 'ELAL-7X9K3',
    notes: '',
  },
];

export const sampleHotels: Hotel[] = [
  {
    id: 'ht-1',
    tripId: 'trip-amsterdam-2026',
    name: 'Hotel V Nesplein',
    city: 'אמסטרדם',
    checkIn: '2026-08-15',
    checkOut: '2026-08-22',
    pricePerNight: 180,
    currency: 'EUR',
    confirmation: 'BK-4521987',
    address: 'Nes 49, 1012 KD Amsterdam',
    notes: 'ארוחת בוקר כלולה, חניה בתשלום',
    rating: 4,
  },
];

export const sampleCarRental: CarRental[] = [
  {
    id: 'cr-1',
    tripId: 'trip-amsterdam-2026',
    company: 'Europcar',
    carType: 'Volkswagen Golf',
    pickupLocation: 'שדה התעופה אמסטרדם סכיפהול',
    dropoffLocation: 'שדה התעופה אמסטרדם סכיפהול',
    pickupDate: '2026-08-17',
    returnDate: '2026-08-20',
    pricePerDay: 65,
    currency: 'EUR',
    confirmation: 'EU-98234',
    notes: 'ביטוח מלא כלול',
  },
];

export const sampleActivities: Activity[] = [
  {
    id: 'act-1',
    tripId: 'trip-amsterdam-2026',
    name: 'מוזיאון ואן גוך',
    date: '2026-08-16',
    time: '10:00',
    location: 'Museumplein 6, Amsterdam',
    price: 22,
    currency: 'EUR',
    category: 'תרבות',
    notes: 'להזמין כרטיסים מראש',
    booked: true,
  },
  {
    id: 'act-2',
    tripId: 'trip-amsterdam-2026',
    name: 'מוזיאון אנה פרנק',
    date: '2026-08-16',
    time: '14:00',
    location: 'Westermarkt 20, Amsterdam',
    price: 16,
    currency: 'EUR',
    category: 'תרבות',
    notes: 'יש להזמין כרטיסים חודשיים מראש',
    booked: true,
  },
  {
    id: 'act-3',
    tripId: 'trip-amsterdam-2026',
    name: 'סיור אופניים בתעלות',
    date: '2026-08-17',
    time: '09:00',
    location: 'מרכז העיר',
    price: 30,
    currency: 'EUR',
    category: 'ספורט',
    notes: 'סיור מודרך 3 שעות',
    booked: false,
  },
  {
    id: 'act-4',
    tripId: 'trip-amsterdam-2026',
    name: 'ריימונד בלומנמרקט',
    date: '2026-08-18',
    time: '11:00',
    location: 'Singel, Amsterdam',
    price: 0,
    currency: 'EUR',
    category: 'קניות',
    notes: 'שוק הפרחים הצף המפורסם',
    booked: false,
  },
  {
    id: 'act-5',
    tripId: 'trip-amsterdam-2026',
    name: 'גינת קיקנהוף',
    date: '2026-08-19',
    time: '10:00',
    location: 'Lisse (40 ק"מ מאמסטרדם)',
    price: 19,
    currency: 'EUR',
    category: 'טבע',
    notes: 'הגן הנחמד ביותר בהולנד',
    booked: false,
  },
  {
    id: 'act-6',
    tripId: 'trip-amsterdam-2026',
    name: 'סעודת ערב — מסעדת Moeders',
    date: '2026-08-20',
    time: '19:30',
    location: 'Rozengracht 251, Amsterdam',
    price: 45,
    currency: 'EUR',
    category: 'אוכל',
    notes: 'מסעדה הולנדית מסורתית, להזמין מקום',
    booked: false,
  },
];

export const sampleBudget: BudgetItem[] = [
  {
    id: 'bud-1',
    tripId: 'trip-amsterdam-2026',
    category: 'טיסות',
    description: 'טיסת הלוך TLV→AMS',
    amount: 1850,
    currency: 'ILS',
    date: '2026-08-15',
    paid: true,
  },
  {
    id: 'bud-2',
    tripId: 'trip-amsterdam-2026',
    category: 'טיסות',
    description: 'טיסת חזור AMS→TLV',
    amount: 1850,
    currency: 'ILS',
    date: '2026-08-22',
    paid: true,
  },
  {
    id: 'bud-3',
    tripId: 'trip-amsterdam-2026',
    category: 'מלונות',
    description: 'Hotel V Nesplein — 7 לילות',
    amount: 1260,
    currency: 'EUR',
    date: '2026-08-15',
    paid: false,
  },
  {
    id: 'bud-4',
    tripId: 'trip-amsterdam-2026',
    category: 'השכרת רכב',
    description: 'Europcar — 3 ימים',
    amount: 195,
    currency: 'EUR',
    date: '2026-08-17',
    paid: false,
  },
  {
    id: 'bud-5',
    tripId: 'trip-amsterdam-2026',
    category: 'פעילויות',
    description: 'כרטיסי מוזיאון ואן גוך',
    amount: 44,
    currency: 'EUR',
    date: '2026-08-16',
    paid: true,
  },
  {
    id: 'bud-6',
    tripId: 'trip-amsterdam-2026',
    category: 'אוכל',
    description: 'תקציב אוכל כולל',
    amount: 400,
    currency: 'EUR',
    date: '2026-08-15',
    paid: false,
  },
];

export const sampleChecklist: ChecklistItem[] = [
  { id: 'chk-1', tripId: 'trip-amsterdam-2026', category: 'מסמכים', text: 'דרכון (תוקף מעל 6 חודשים)', checked: true },
  { id: 'chk-2', tripId: 'trip-amsterdam-2026', category: 'מסמכים', text: 'כרטיסי טיסה מודפסים', checked: false },
  { id: 'chk-3', tripId: 'trip-amsterdam-2026', category: 'מסמכים', text: 'אישורי מלון', checked: false },
  { id: 'chk-4', tripId: 'trip-amsterdam-2026', category: 'מסמכים', text: 'ביטוח נסיעות', checked: true },
  { id: 'chk-5', tripId: 'trip-amsterdam-2026', category: 'מסמכים', text: 'כרטיס אשראי בינלאומי', checked: true },
  { id: 'chk-6', tripId: 'trip-amsterdam-2026', category: 'בגדים', text: 'מעיל גשם', checked: false },
  { id: 'chk-7', tripId: 'trip-amsterdam-2026', category: 'בגדים', text: 'נעלי הליכה נוחות', checked: true },
  { id: 'chk-8', tripId: 'trip-amsterdam-2026', category: 'בגדים', text: 'בגדים ל-7 ימים', checked: false },
  { id: 'chk-9', tripId: 'trip-amsterdam-2026', category: 'אלקטרוניקה', text: 'מטען נסיעות אירופי', checked: false },
  { id: 'chk-10', tripId: 'trip-amsterdam-2026', category: 'אלקטרוניקה', text: 'מצלמה', checked: true },
  { id: 'chk-11', tripId: 'trip-amsterdam-2026', category: 'אלקטרוניקה', text: 'ספריית מוזיקה / פודקאסטים להורדה', checked: false },
  { id: 'chk-12', tripId: 'trip-amsterdam-2026', category: 'תרופות', text: 'תרופות שגרתיות', checked: false },
  { id: 'chk-13', tripId: 'trip-amsterdam-2026', category: 'תרופות', text: 'קרם הגנה', checked: false },
  { id: 'chk-14', tripId: 'trip-amsterdam-2026', category: 'ציוד', text: 'מטריה', checked: false },
  { id: 'chk-15', tripId: 'trip-amsterdam-2026', category: 'ציוד', text: 'מנעול לכבודה', checked: true },
];
